baseURL = "https://www.irohaka.com/"
title = "イロハカの自転車日記"

languageCode = "ja-jp"
hasCJKLanguage = true
theme = "DoNormal"
dateFormat = "2006年01月02日"
disqusShortname = "irohaka"

[Params]
    author = "IROHAKA"
    images = ["img/eyecache.jpg"]
    description ="イロハカの自転車と旅行と趣味のはなしをメインに書いています。"
    amazonJpAffiliate = "irohaka-22"
    tags = "自転車, ブログ"
    

[outputs]
  page = ["HTML" , "RSS"]
  Home = ["HTML" , "RSS"]

disqusShortname = "irohaka-netlify-com"

[taxonomies]
    tag = "tags"

[[menu.main]]
  name = "TOPページ"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/pages/about/"
  weight = 2

  # let hugo automatically resize and crop your images to the correct sizes
    resizeImages = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = true
    latexDashes = true
    nofollowLinks = true
    extensionsmask = ["autolink"]
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true

    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xHTML = false

   [markup.highlight]
     codeFences = true
     guessSyntax = false
     hl_Lines = ""
     lineNoStart = 1
     lineNos = false
     lineNumbersInTable = true
     noClasses = true
     style = "monokai"
     tabWidth = 4

   [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2