baseURL = "https://irohaka.com/"
title = "イロハカの自転車日記"

languageCode = "ja-jp"
hasCJKLanguage = true
theme = "Supernormal"
dateFormat = "2006年01月02日"
disqusShortname = "irohaka"

[Params]
    author = "IROHAKA"
    images = ["img/eyecatch.jpg"]
    description ="イロハカの自転車と旅行と趣味のはなし。"
    amazonJpAffiliate = "irohaka-22"

[outputs]
  page = ["HTML", "AMP"]
  Home = ["HTML", "AMP"]

[blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    extensionsmask = ["autolink"]

[taxonomies]
    tag = "tags"

[[menu.main]]
  name = "TOPページ"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2