baseURL = "http://example.org/"
title = "New Hugo Supernormal Site"
languageCode = "ja-jp"
hasCJKLanguage = true
theme = "Supernormal"


[Params]
    author = "Hoge"
    profile_image = "images/profile.jpg"
    featured_image = "images/cover.svg"

[blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    extensionsmask = ["autolink"]