baseURL = "https://www.irohaka.com/"
title = "イロハカの自転車日記"

languageCode = "ja-jp"
hasCJKLanguage = true
theme = "DoNormal"
dateFormat = "2006年01月02日"
disqusShortname = "irohaka"

[Params]
    author = "IROHAKA"
    images = ["img/eyecatch.jpg"]
    description ="イロハカの自転車と旅行と趣味のはなしをメインに書いています。"
    amazonJpAffiliate = "irohaka-22"
    tags = "自転車, ブログ"
    
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  page = ["HTML", "AMP" , "RSS"]
  Home = ["HTML", "AMP" , "RSS"]

disqusShortname = "irohaka-netlify-com"

[blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    extensionsmask = ["autolink"]

[taxonomies]
    tag = "tags"

[[menu.main]]
  name = "TOPページ"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2