baseURL = "https://irohaka.netlify.com/"
title = "イロハカの自転車日記"
languageCode = "ja-jp"
hasCJKLanguage = true
theme = "Supernormal"

disqusShortname = "irohaka"

[Params]
    author = "IROHAKA"
    featured_image = "img/eyecatch.jpg"

[blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    extensionsmask = ["autolink"]

[taxonomies]
    tag = "tags"
