baseURL = "https://irohaka.netlify.com/"
title = "イロハカの自転車日記"
languageCode = "ja-jp"
hasCJKLanguage = true
theme = "Supernormal"

disqusShortname = "irohaka"

[Params]
    author = "Hoge"
    profile_image = "images/profile.jpg"
    featured_image = "images/cover.svg"

[blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    extensionsmask = ["autolink"]

