baseURL = "https://irohaka.netlify.com/"
title = "イロハカの自転車日記"
languageCode = "ja-jp"
hasCJKLanguage = true
theme = "Supernormal"

disqusShortname = "irohaka"

[Params]
    author = "IROHAKA"
    images = ["img/eyecatch.jpg"]
    addThis = "ra-5d5fad14f7600d5b"

[blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    extensionsmask = ["autolink"]

[taxonomies]
    tag = "tags"

[[menu.main]]
  name = "TOPページ"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2